import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WalletContextProvider from '@/components/Wallet/WalletContextProvider';
import { AntdThemeProvider } from '@/components/Antd/AntdThemeProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SSI Solana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout");
  return (
    <html lang="en">
      <WalletContextProvider>
        <AntdThemeProvider>
          <body className={inter.className}>{children}</body>
        </AntdThemeProvider>
      </WalletContextProvider>
    </html>
  );
}
